
- name: install MySQL Server packages
  apt: name={{ item }}  state=present force=yes update_cache=yes
  with_items:
    - software-properties-common
    - mysql-server
    #- python-mysqldb

- name: install pip package required for creating users
  pip:
    name: mysqlclient
    version: 1.3.9

- include: users.yml