- mysql_user:
    name: '{{ mysql_user }}'
    password: '{{ mysql_pass }}'
    priv: '*.*:ALL'
    state: present

- name: Create a new database
  mysql_db:
    name: '{{ mysql_db }}'
    state: present
