# Install base pacakges as required
- name: Ensure bash, OpenSSL, and libssl are the latest versions
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc

- name: Install base packages
  apt: name={{ item }} update_cache=yes force=yes state=installed
  with_items:
    - build-essential
    - acl
    - ntp
    - htop
    - git
    - libpq-dev
    - libmysqlclient-dev # required to install pip package 'mysqlclient' in mysql role
    - python-dev
    - python3-pip
    - python-pycurl
    - ipython

- name: install virtual env
  pip: name={{ item }}
  with_items:
    - virtualenv
    #- virtualenvwrapper

- name: set the locales to the en_CA.UTF-8
  locale_gen: name=en_CA.UTF-8 state=present

- name: create the directories for app deployment
  file: path={{ item }} state=directory
  with_items:
  - /srv/apps
  - /srv/apps/virtualenvs
