# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-17 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20170217_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Name')),
                ('favorite_color', models.CharField(max_length=250, verbose_name='Favorite Color')),
                ('cats_or_dogs', models.CharField(max_length=250, verbose_name='Cats or Dogs?')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
    ]
