# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-17 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form',
        ),
    ]
