# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-20 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_auto_20170218_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='cats_or_dogs',
            field=models.CharField(choices=[('CAT', 'Cats'), ('DOG', 'Dogs')], default='CAT', max_length=4),
        ),
    ]
