- include: setup_git_repo.yml

- name: Create the virtualenv
  command: virtualenv {{ virtualenv_path }}
           creates={{ virtualenv_path }}/bin/activate

- include: setup_app.yml

- include: setup_uwsgi.yml